In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pickle 
import math
import tables

In [ ]:
#

In [2]:
tempArray = np.full((64**2,512,512), np.nan )
#Max size is around : 1073741824

In [3]:
temp2 = np.full((64**2,512,512), np.nan )

In [4]:
temp3 = np.full((64**2,512,512), np.nan )

In [6]:
print(tempArray[0,0:64,0:64])
np.random.rand(64,64)
tempArray[0,0:64,0:64]=  np.random.rand(64,64)

[[0.4858709  0.5841379  0.30038771 ... 0.80356044 0.72662374 0.85329522]
 [0.02008628 0.41842507 0.73777277 ... 0.96479533 0.18624377 0.9952192 ]
 [0.06882137 0.26619889 0.35608108 ... 0.94625455 0.33733427 0.4865047 ]
 ...
 [0.0542277  0.85262102 0.54894948 ... 0.50126929 0.5553265  0.93855586]
 [0.01670121 0.22006872 0.52438689 ... 0.08556445 0.96509558 0.46702096]
 [0.63572334 0.89555565 0.16518302 ... 0.1611506  0.58597694 0.8172121 ]]


In [15]:
print(np.all(tempArray[3,0,0]))

True


In [ ]:
#Coede to determine if we can save here... order is unimportant
    #If we were more clever we could probably figure out exactly where to save each time but I am not feeling clever today
index = 0
while np.all(np.isnan(tempArray[index,0:64,0:64])) == False:
    index += 1
if np.all(np.isnan(tempArray[index,0:64,0:64])):
    print('youpiee')
else:
    print('Pesky little data')

Pesky little data


In [41]:
#ZARR?
import zarr 

In [42]:
store = zarr.storage.LocalStore('mydata.zarr')
zarr_data = zarr.create_array(
    store=self.store, 
    name='data',
    shape=(40000, 100), 
    chunks=(1000, 100), 
    dtype='f4')

zarr_data[:] = np.random.randn(10000, 100)

NameError: name 'self' is not defined